### ISSUE TITLE
How to scan a specific URL?

### ISSUE THREAD

**Issue by nguoianphu** [integrissecurity/carbonator#5]
How to scan a fqdn with a path?
I want to scan this URL: `http 127.0.0.1/app/ 80 /folder` instead of  `http 127.0.0.1 80 /folder`. But it doesn't work.

**Comment by nguoianphu** [comment]
I'd misunderstood...
`java -jar burpsuite_pro_v1.6.28.jar http 127.0.0.1 80 /app`

**Comment by integrissecurity** [comment]
Glad this is resolved. Let us know if there is anything else that comes up.
